services:
#    my_contact.example:
#        class: %my_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    page.form.contact:
        class: My\ContactBundle\Form\ContactType    
        arguments: [@security.context]    
        tags:
            - { name: form.type, alias: contact_form }

    contact.mailer:
        class: My\ContactBundle\Mailer\Mailer
        arguments: [@mailer,@templating,'%mailer.emails.contact%']