parameters:
#    my_contact.example.class: My\ContactBundle\Example

services:
#    my_contact.example:
#        class: %my_contact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    page.form.contact:
        class: My\ContactBundle\Form\ContactType        
        tags:
            - { name: form.type, alias: contact_form }

    contact.mailer:
        class: My\ContactBundle\Mailer\mailer
        arguments: [@mailer,@templating]