parameters:
#    ws_statistic.example.class: Ws\StatisticBundle\Example

services:
#    ws_statistic.example:
#        class: %ws_statistic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    statistic.manager:
        class: Ws\StatisticBundle\Manager\StatisticManager
        arguments: [@service_container]

    daily_statistic.manager:
        class: Ws\StatisticBundle\Manager\DailyStatisticManager
        arguments: [@service_container]

    statistic.mailer:
        class: Ws\StatisticBundle\Mailer\Mailer
        arguments: [@mailer,@templating,'%mailer.sender.noreply%']
        tags:
            - { name: statistic_mailer, alias: statistic_mailer }