parameters:
#    ws_statistic.example.class: Ws\StatisticBundle\Example

services:
#    ws_statistic.example:
#        class: %ws_statistic.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    statistic.manager:
        class: Ws\StatisticBundle\Manager\StatisticManager
        arguments: [@service_container]