my_utils_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MyUtilsBundle:Default:index }

my_utils_testobject:
    pattern: /object/test
    defaults: {_controller: MyUtilsBundle:TestObject:testObjectChange }