parameters:
#    my_utils.example.class: My\UtilsBundle\Example

services:
#    my_utils.example:
#        class: %my_utils.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
