parameters:
#    my_utils.example.class: My\UtilsBundle\Example

services:
#    my_utils.example:
#        class: %my_utils.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    my_utils_bundle.tags_type:
        class: My\UtilsBundle\Form\Type\TagsType
        tags:
            - { name: form.type, alias: tags }

#Profiler matcher
    my_utils.profiler_matcher:
        class: My\UtilsBundle\Profiler\Matcher
        arguments: ["@security.context"]


#Twig extension
    utils.twig.age_calculator:
        class: My\UtilsBundle\Twig\AgeCalculatorExtension
        tags:
            - { name: twig.extension }
    utils.twig.giphy:
        class: My\UtilsBundle\Twig\GiphyExtension
        tags:
            - { name: twig.extension }