<?php

namespace Ws\EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertRepository extends EntityRepository
{
	public function findDailyAlerts()
	{

		$qb = $this->createQueryBuilder('a');
		$qb->andWhere($qb->expr()->eq('a.active',true));
		$qb->andWhere($qb->expr()->eq('a.frequency',':frequency'))->setParameter('frequency','daily');

		return $qb->getQuery()->getResult();
	}

	public function findWeeklyAlerts()
	{

		$qb = $this->createQueryBuilder('a');
		$qb->andWhere($qb->expr()->eq('a.active',true));
		$qb->andWhere($qb->expr()->eq('a.frequency',':frequency'))->setParameter('frequency','weekly');

		return $qb->getQuery()->getResult();
	}
}
