<?php

namespace Ws\EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;

use Ws\EventsBundle\Entity\InvitationBlacklist;

/**
 * InvitationBlacklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationBlacklistRepository extends EntityRepository
{
	public function addEmailsToBlacklist($emails)
	{
		foreach ($emails as $key => $email) {
			
			$blacklisted = new InvitationBlacklist();
			$blacklisted->setEmail($email);
			$this->_em->persist($blacklisted);
			
		}

		$this->_em->flush();
	}

	public function removeEmailsFromBlacklist($emails)
	{
		foreach ($emails as $key => $email) {
			
			$blacklisted = $this->findOneByEmail($email);
			
			if($blacklisted == null) continue;

			$this->_em->remove($blacklisted);
		}

		$this->_em->flush();
	}
}
