<?php

namespace Ws\EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;


use Ws\EventsBundle\Entity\Participation;
/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitedRepository extends EntityRepository
{
	public function findOneRandomly()
	{
		$sql = 'SELECT i.id, i.email FROM WsEventsBundle:Invited i';
		$query = $this->getEntityManager()->createQuery($sql);
		$ids = $query->getScalarResult();

		$randomId = $ids[array_rand($ids)];

		$invit = $this->_em->getRepository('WsEventsBundle:Invited')->find($randomId);
		return $invit;
	}
	
	public function hasResponded($invited)
	{
		$invit = $this->_em->getRepository('WsEventsBundle:Invited')->find($invited);		
		return $invit->getResponse();
	}

	public function removeInvited($invited)
	{
		$this->_em->remove($invited);
		$this->_em->flush();
	}

	public function confirmParticipation($invited)
	{
		if($this->hasResponded($invited) == true) return; //already confirmed

		if(null != $invited->getUser() && $this->_em->getRepository('WsEventsBundle:Participation')->isUserParticipating($invited->getUser(),$invited->getInvitation()->getEvent())) return;

		$participant = new Participation();
		$participant->setEvent($invited->getInvitation()->getEvent());
		$participant->setUser($invited->getUser()); //is null if the invited user is not registered
		$participant->setInvited($invited);

		$this->_em->getRepository('WsEventsBundle:Participation')->saveParticipation($participant);

		$invited->setResponse(true);
		$invited->setDateResponse('now');
		$this->_em->persist($invited);
		$this->_em->flush();
	}

	public function denyParticipation($invited)
	{
		if($this->hasResponded($invited) === false) return; //already denied

		$invited->setResponse(false);
		$invited->setDateResponse('now');		

		$this->_em->persist($invited);
		$this->_em->flush();

		$this->_em->getRepository('WsEventsBundle:Participation')->findParticipationAndRemove($invited->getInvitation()->getEvent(),null,$invited);
	}

	public function findByUserAndIsLikeEmail($user,$search)
	{
		$qb = $this->createQueryBuilder('i');

		if(null==$user) return null;

		$qb->andWhere($qb->expr()->eq('i.user',':user'))->setParameter('user',$user);

		if(is_string($search) && !empty($search))
			$qb->andWhere($qb->expr()->like('i.email',$qb->expr()->literal('%'.$search.'%')));

		return $qb->getQuery()->getResult();
	}
	
		
}
