<?php

namespace Ws\EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Ws\EventsBundle\Entity\Participation;

/**
 * EventParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends EntityRepository
{
	public function findParticipation($event,$user=null,$invited=null)
	{
		$qb = $this->createQueryBuilder('p');
		$qb->andWhere('p.event = :event')->setParameter('event',$event);

		if(isset($user))
			$qb->andWhere('p.user = :user')->setParameter('user',$user);
		if(isset($invited))
			$qb->andWhere('p.invited = :invited')->setParameter('invited',$invited);			

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findParticipationAndRemove($event,$user=null,$invited=null)
	{
		$particip = $this->findParticipation($event,$user,$invited);
		if(isset($particip))
			return $this->removeParticipation($particip);
		return false;
	}


	public function saveParticipation(Participation $particip)
	{
		$this->_em->persist($particip);
		$this->_em->flush();
		return true;
	}

	public function removeParticipation(Participation $particip)
	{
		$this->_em->remove($particip);
		$this->_em->flush();
		return true;
	}

}
