<?php

namespace Ws\EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;

use My\UserBundle\Entity\User;
use Ws\EventsBundle\Entity\Participation;
use Ws\EventsBundle\Entity\Invited;
use Ws\EventsBundle\Entity\Event;
/**
 * EventParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends EntityRepository
{
	public function findParticipation($event,$user=null,$invited=null)
	{
		$qb = $this->createQueryBuilder('p');
		$qb->andWhere('p.event = :event')->setParameter('event',$event);

		if(isset($user))
			$qb->andWhere('p.user = :user')->setParameter('user',$user);
		if(isset($invited))
			$qb->andWhere('p.invited = :invited')->setParameter('invited',$invited);			

		return $qb->getQuery()->getOneOrNullResult();
	}

	public function findRecentlyPosted($nb = 10)
	{
		$qb = $this->createQueryBuilder('p');
		$qb->select('p')
			->orderBy('p.date_inscription','DESC')
			->setMaxResults($nb);

		return $qb->getQuery()->getResult();
	}

	public function findComingSoon($nb=10)
	{
		$qb = $this->createQueryBuilder('p');		

		$qb->select('p')
			->orderBy('p.date_inscription','ASC')->andWhere($qb->expr()->lte('p.date_inscription','CURRENT_DATE()'))			
			->setMaxResults($nb)
		;

		return $qb->getQuery()->getResult();
	}
	public function isUserParticipating(User $user,Event $event)
	{
		return (null !== $this->findParticipation($event,$user))? true : false;
	}

	public function findParticipationAndRemove(Event $event,User $user=null,Invited $invited=null)
	{
		$particip = $this->findParticipation($event,$user,$invited);
		if(isset($particip))
			return $this->removeParticipation($particip);
		return false;
	}


	public function saveParticipation(Participation $particip)
	{
		$this->_em->persist($particip);
		$this->_em->flush();
		return true;
	}

	public function removeParticipation(Participation $particip)
	{
		$this->_em->remove($particip);
		$this->_em->flush();
		return true;
	}

	public function countAll()
	{
		return $this->createQueryBuilder('e')
				 ->select('COUNT(e)')
				 ->getQuery()
				 ->getSingleScalarResult();
	}

}
