<?php

namespace Ws\EventsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpotRepository extends EntityRepository
{

	public function findSuggestions($limit = 10,$search = '',$countryCode = null)
	{
		$qb = $this->createQueryBuilder('s');

		if(isset($countryCode))
			$qb->andWhere($qb->expr()->eq('s.countryCode',$qb->expr()->literal($countryCode)));

		if($terms = preg_split("/(,| |\.)/",$search)){
			foreach ($terms as $term) {
				if(!empty($term) && strlen($term)>2){

					$qb->andWhere($qb->expr()->like('s.slug',$qb->expr()->literal('%'.$term.'%')));
				}
			}
		}

		$qb->setMaxResults($limit);
		$qb->orderBy('s.slug','DESC');

		return $qb->getQuery()->getResult();
	}	

}
