<?php

namespace Ws\EventsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventParticipantsRepository extends EntityRepository
{
	public function persist($entity)
	{
		$this->_em->persist($entity);
	}

	public function persistAndFlush($entity)
	{
		$this->_em->persist($entity);
		$this->_em->flush();
	}

}
