<?php

namespace Ws\EventsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InvitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationRepository extends EntityRepository
{
	public function findOneRandomly()
	{
		$sql = 'SELECT i.id FROM WsEventsBundle:Invitation i';
		$query = $this->getEntityManager()->createQuery($sql);
		$ids = $query->getScalarResult();

		$randomId = $ids[array_rand($ids)];

		$invit = $this->_em->getRepository('WsEventsBundle:Invitation')->find($randomId);
		return $invit;
	}

	public function findSavedInvitation($user)
	{
		$qb = $this->createQueryBuilder('i');
		$qb->andWhere($qb->expr()->eq('i.inviter',':user'));
		$qb->andWhere($qb->expr()->isNotNull('i.name'));
		$qb->setParameter('user',$user);
		return $qb->getQuery()->getResult();	
	}

}
