<?php

namespace Ws\EventsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventParticipantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends EntityRepository
{
	public function findParticipation($event,$user)
	{
		$qb = $this->createQueryBuilder('p');
		$qb->where('p.event',':event')
			->andWhere('p.user',':user')
			->setParameter('user',$user)
			->setParameter('event',$event)
			;

		return $qb->getQuery->getOneOrNullResult();
	}

}
