<?php

namespace Ws\StatisticBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Ws\StatisticBundle\Entity\GlobalStat;

/**
 * StatisticRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalStatRepository extends EntityRepository
{
	public function initStat($name = 'main')
	{
		$stat = new GlobalStat();
		$stat->setName($name);

		$this->_em->persist($stat);
		$this->_em->flush();
	}
}
