<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20140123140222 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql", "Migration can only be executed safely on 'mysql'.");
        
        $this->addSql("DROP TABLE world_cities");
        $this->addSql("DROP TABLE world_regions");
        $this->addSql("DROP TABLE world_states");
        $this->addSql("ALTER TABLE world_country DROP INDEX CC1, ADD UNIQUE INDEX UNIQ_BC36E731717F677 (CC1)");
        $this->addSql("ALTER TABLE world_country DROP REGION_ID, DROP ISO_4217, CHANGE id id INT NOT NULL, CHANGE LO LO VARCHAR(3) NOT NULL, CHANGE ISO_ALPHA2 ISO_ALPHA2 VARCHAR(2) NOT NULL, CHANGE ISO_NUMERIC ISO_NUMERIC SMALLINT NOT NULL, CHANGE INTERNET INTERNET VARCHAR(2) NOT NULL, CHANGE CC2 CC2 VARCHAR(2) NOT NULL, CHANGE COMMENT COMMENT VARCHAR(255) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql", "Migration can only be executed safely on 'mysql'.");
        
        $this->addSql("CREATE TABLE world_cities (id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHAR_CODE TINYINT(1) NOT NULL, UFI INT NOT NULL, UNI INT NOT NULL, CC1 CHAR(2) NOT NULL, DSG VARCHAR(5) NOT NULL, ADM1 CHAR(3) NOT NULL, ADM2 VARCHAR(3) NOT NULL, ADM3 VARCHAR(3) NOT NULL, ADM4 VARCHAR(3) NOT NULL, NT CHAR(1) NOT NULL, LC CHAR(3) NOT NULL, SHORTFORM VARCHAR(128) NOT NULL, FULLNAME VARCHAR(200) NOT NULL, FULLNAMEND VARCHAR(200) NOT NULL, CHARACTERS VARCHAR(24) NOT NULL, LATITUDE DOUBLE PRECISION NOT NULL, LONGITUDE DOUBLE PRECISION NOT NULL, DMSLAT INT NOT NULL, DMSLONG INT NOT NULL, INDEX UNI (UNI), INDEX FULLNAME_2 (FULLNAME), INDEX FindCities (CC1, ADM1, ADM2, ADM3, ADM4), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE world_regions (REGION_ID INT DEFAULT NULL, REGION_PARENT VARCHAR(3) DEFAULT NULL, REGION_NAME VARCHAR(56) DEFAULT NULL, LC VARCHAR(3) DEFAULT NULL, CHARACTERS VARCHAR(18) DEFAULT NULL) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE world_states (CHAR_CODE INT DEFAULT NULL, UFI INT DEFAULT NULL, UNI INT DEFAULT NULL, CC1 VARCHAR(2) DEFAULT NULL, DSG VARCHAR(4) DEFAULT NULL, ADM_PARENT VARCHAR(3) DEFAULT NULL, ADM_CODE VARCHAR(3) DEFAULT NULL, NT VARCHAR(1) DEFAULT NULL, LC VARCHAR(3) DEFAULT NULL, SHORTFORM VARCHAR(56) DEFAULT NULL, FULLNAME VARCHAR(83) DEFAULT NULL, FULLNAMEND VARCHAR(79) DEFAULT NULL, CHARACTERS VARCHAR(18) DEFAULT NULL, INDEX FindStates (CC1, ADM_PARENT, DSG), INDEX findAState (ADM_CODE), FULLTEXT INDEX NAME (FULLNAME)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE world_country DROP INDEX UNIQ_BC36E731717F677, ADD INDEX CC1 (CC1)");
        $this->addSql("ALTER TABLE world_country ADD REGION_ID INT UNSIGNED NOT NULL, ADD ISO_4217 CHAR(3) NOT NULL, CHANGE id id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE LO LO CHAR(3) DEFAULT 'eng' NOT NULL, CHANGE ISO_ALPHA2 ISO_ALPHA2 CHAR(2) NOT NULL, CHANGE ISO_NUMERIC ISO_NUMERIC TINYINT(1) NOT NULL, CHANGE INTERNET INTERNET CHAR(2) NOT NULL, CHANGE CC2 CC2 CHAR(2) NOT NULL, CHANGE COMMENT COMMENT LONGTEXT NOT NULL");
    }
}
