imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator: ~
    #translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - ':Form:fields.html.twig'
            - ':Form:buttons.html.twig' 
            - 'MyWorldBundle:Form:location_selectboxs.html.twig' 

# Activate Twig Extension
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles: 
        - "FOSCommentBundle"
        - "AcmeTwigBundle"
        - "WsSportsBundle"
        - "WsEventsBundle"
        - "WsStyleBundle"
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        logging: false
        profiling: false
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable #this one is optional and will default to the name set for the mapping
                        is_bundle: false
                dql:
                   numeric_functions:
                       power: My\WorldBundle\DQL\Power
                       asin: My\WorldBundle\DQL\Asin
                       sin: My\WorldBundle\DQL\Sin
                       pi : My\WorldBundle\DQL\Pi
                       cos: My\WorldBUndle\DQL\Cos


# Doctrine Extension Bundle Configuration
stof_doctrine_extensions:
    default_locale: fr_FR
    translation_fallback: true
    orm:
        default:
            translatable: true
            sluggable: true

# I18n routing Configuration
jms_i18n_routing:
    default_locale: fr
    locales: [fr, en]
    strategy: prefix #prefix_except_default


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Fos
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: My\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: true
        form:
            type: my_user_registration
    from_email:
        address: noreply@demosf2.com
        sender_name: demosf2
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            template: MyUserBundle:ChangePassword:email.txt.twig

fos_comment:
    db_driver: orm
    class:
        model:
            comment: My\CommentBundle\Entity\Comment
            thread: My\CommentBundle\Entity\Thread
    #security permission
    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
    acl_roles:
        comment:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
