imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            1
    strict_variables: "%kernel.debug%"
    globals:
        app_version: "%app.version%"
        app_facebook_id: "%oauth.facebook.id%"
    form:
        resources:
            - ':Form:field.html.twig'
            - ':Form:fields.html.twig'
            - ':Form:buttons.html.twig' 
            - 'MyWorldBundle:Form:location_selectboxs.html.twig' 
            - 'MyUtilsBundle:Form:field_tags.html.twig'
            - 'WsSportsBundle:Form:select_multiple.html.twig'

# Activate Twig Extension
services:
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: twig.extension }


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles: 
        - "FOSCommentBundle"
        - "WsSportsBundle"
        - "WsEventsBundle"
        - "WsStyleBundle"
        - "MyUtilsBundle"
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
                logging: false
                profiling: false
            oldwesport:
                dbname: "%old_database_name%"
                user: "%old_database_user%"
                password: "%old_database_password%"
                host: "%old_database_host%"
                charset: UTF8
                logging: false
                profiling: false
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                auto_mapping: true
                mappings:
                    gedmo_translatable:
                        type: annotation
                        prefix: Gedmo\Translatable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                        alias: GedmoTranslatable #this one is optional and will default to the name set for the mapping
                        is_bundle: false
                dql:
                    numeric_functions:
                        power: My\WorldBundle\DQL\Power
                        asin: My\WorldBundle\DQL\Asin
                        sin: My\WorldBundle\DQL\Sin
                        pi : My\WorldBundle\DQL\Pi
                        cos: My\WorldBundle\DQL\Cos
                    datetime_functions:
                        DAYNAME: My\UtilsBundle\DQL\Dayname
                        DAY: My\UtilsBundle\DQL\Day
                        MONTH: My\UtilsBundle\DQL\Month
                        YEAR: My\UtilsBundle\DQL\Year


# Doctrine Extension Bundle Configuration
stof_doctrine_extensions:
    default_locale: fr_FR
    translation_fallback: true
    orm:
        default:
            translatable: true
            sluggable: true

# I18n routing Configuration
jms_i18n_routing:
    default_locale: fr
    locales: [fr, en]
    strategy: prefix #prefix_except_default


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Fos
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: My\UserBundle\Entity\User
    registration:
        confirmation:
            enabled: true 
            template: MyUserBundle:Registration:email.html.twig
        form:
            type: my_user_registration
    profile:
        form:
            type: my_user_profile
    from_email:
        address: contact@cosporturage.fr
        sender_name: cosporturage.fr
    service:
        mailer: my_user.mailer
    resetting:
        email:
            template: MyUserBundle:Resetting:email.html.twig

#Hwi Oauth 
hwi_oauth:
    firewall_name: main
    use_referer: true
    resource_owners:
        facebook:
            type: facebook
            client_id: %oauth.facebook.id%
            client_secret: %oauth.facebook.secret%
            scope: "email,user_birthday"
            options:
                display: popup



#Fos Comment bundle
fos_comment:
    db_driver: orm
    class:
        model:
            comment: My\CommentBundle\Entity\Comment
            thread: My\CommentBundle\Entity\Thread
    #security permission
    acl: true
    service:
        acl:
            thread:  fos_comment.acl.thread.roles
            comment: fos_comment.acl.comment.roles
            vote:    fos_comment.acl.vote.roles
        manager:
            thread:  fos_comment.manager.thread.acl
            comment: fos_comment.manager.comment.acl
            vote:    fos_comment.manager.vote.acl
    acl_roles:
        comment:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        thread:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN
        vote:
            create: IS_AUTHENTICATED_ANONYMOUSLY
            view: IS_AUTHENTICATED_ANONYMOUSLY
            edit: ROLE_ADMIN
            delete: ROLE_ADMIN

#Sonata admin-bundle
sonata_admin:
    title: coSporturage
    title_logo: /web/bundles/wsstyle/img/LOGO.gif
    templates:
        layout: MyUtilsBundle:Administration:standard_layout.html.twig
        search:              SonataAdminBundle:Core:search.html.twig
        search_result_block: SonataAdminBundle:Block:block_search_result.html.twig
    dashboard:
        blocks:
            -
                position: left
                type: sonata.block.service.welcome        
            -
                position: left
                type: sonata.block.service.recent_events
            -
                position: left
                type: sonata.block.service.recent_participations
            #-
            #    position: left
            #    type: sonata.admin.block.admin_list
               
            -
                position: right
                type: sonata.block.service.coming_events 
            -
                position: right
                type: sonata.block.service.coming_participations                        


sonata_doctrine_orm_admin:
    templates:
        types:
            list:



#Sonata block-bundle
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.search_result:
           contexts: [admin]
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.block.service.recent_events: ~
        sonata.block.service.recent_participations: ~
        sonata.block.service.coming_events: ~
        sonata.block.service.coming_participations: ~
        sonata.block.service.welcome: ~

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media: