ws_convert_sql:
    resource: "@WsConvertSQLBundle/Resources/config/routing.yml"
    prefix:   /convert

ws_statistic:
    resource: "@WsStatisticBundle/Resources/config/routing.yml"
    prefix:   /stats

my_utils:
    resource: "@MyUtilsBundle/Resources/config/routing.yml"
    prefix:   /

my_contact:
    resource: "@MyContactBundle/Resources/config/routing.yml"
    prefix:   /

ws_mailer:
    resource: "@WsMailerBundle/Resources/config/routing.yml"
    prefix:   /mailer

ws_style:
    resource: "@WsStyleBundle/Resources/config/routing.yml"
    prefix:   /

my_manager:
    resource: "@MyManagerBundle/Resources/config/routing.yml"
    prefix:   /

my_flash:
    resource: "@MyFlashBundle/Resources/config/routing.yml"
    prefix:   /flashbag

my_world:
    resource: "@MyWorldBundle/Resources/config/routing.yml"
    prefix:   /world

ws_events:
    resource: "@WsEventsBundle/Resources/config/routing.yml"
    prefix:   /event

ws_sports:
    resource: "@WsSportsBundle/Resources/config/routing.yml"
    prefix:   /sports

my_comment:
    resource: "@MyCommentBundle/Resources/config/routing.yml"
    prefix:   /

my_page:
    resource: "@MyPageBundle/Resources/config/routing.yml"
    prefix:   /

acme_twig:
    resource: "@AcmeTwigBundle/Resources/config/routing.yml"
    prefix:   /

user_bundle:
    resource: "@MyUserBundle/Resources/config/routing.yml"
    prefix:   /

blog_bundle:
    resource: "@MyBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

accueil:
    resource: "@MyBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

#Sonata admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
###

#redirect url/ to url
#(must be the last route)
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: MyUtilsBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET|POST]