hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /oauth-login
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /oauth-connect
facebook_login:
    pattern: /login/check-facebook

ws_events_calendar:
    resource: "@WsEventsBundle/Resources/config/routing/calendar.yml"
    prefix: /calendar

ws_events_event:
    resource: "@WsEventsBundle/Resources/config/routing/event.yml"
    prefix: /event

ws_events_follower:
    resource: "@WsEventsBundle/Resources/config/routing/follower.yml"
    prefix: /follower 

ws_events_serie:
    resource: "@WsEventsBundle/Resources/config/routing/serie.yml"
    prefix: /serie  

ws_events_spot:
    resource: "@WsEventsBundle/Resources/config/routing/spot.yml"
    prefix: /spot 

ws_events_participant:
    resource: "@WsEventsBundle/Resources/config/routing/participant.yml"
    prefix: /participant 

ws_events_invitation:
    resource: "@WsEventsBundle/Resources/config/routing/invitation.yml"
    prefix: /invitation   

ws_events_alert:
    resource: "@WsEventsBundle/Resources/config/routing/alert.yml"
    prefix: /alert  

ws_events_admin:
    resource: "@WsEventsBundle/Resources/config/routing/admin.yml"
    prefix: /events/admin  

ws_convert_sql:
    resource: "@WsConvertSQLBundle/Resources/config/routing.yml"
    prefix:   /convert

ws_statistic:
    resource: "@WsStatisticBundle/Resources/config/routing.yml"
    prefix:   /stats

my_utils:
    resource: "@MyUtilsBundle/Resources/config/routing.yml"
    prefix:   /utils

my_contact:
    resource: "@MyContactBundle/Resources/config/routing.yml"
    prefix:   /

ws_mailer:
    resource: "@WsMailerBundle/Resources/config/routing.yml"
    prefix:   /mailer

ws_style:
    resource: "@WsStyleBundle/Resources/config/routing.yml"
    prefix:   /

my_manager:
    resource: "@MyManagerBundle/Resources/config/routing.yml"
    prefix:   /

my_flash:
    resource: "@MyFlashBundle/Resources/config/routing.yml"
    prefix:   /flashbag

my_world:
    resource: "@MyWorldBundle/Resources/config/routing.yml"
    prefix:   /world

ws_sports:
    resource: "@WsSportsBundle/Resources/config/routing/sport.yml"
    prefix:   /sports

ws_sports_category:
    resource: "@WsSportsBundle/Resources/config/routing/category.yml"
    prefix:   /sports/category

my_comment:
    resource: "@MyCommentBundle/Resources/config/routing.yml"
    prefix:   /

my_page:
    resource: "@MyPageBundle/Resources/config/routing.yml"
    prefix:   /

user_bundle:
    resource: "@MyUserBundle/Resources/config/routing.yml"
    prefix:   /

blog_bundle:
    resource: "@MyBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

my_cron:
    resource: "@MyCronBundle/Resources/config/routing.yml"
    prefix:   /cron


accueil:
    resource: "@MyBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

#root default page
root:
    pattern: /
    defaults: 
        _controller: FrameworkBundle:Redirect:redirect
        route: ws_calendar
        permanent: true

#sonata admin
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

#reformatting url/ to url
#(must be the last route)
remove_trailing_slash:
    path: /{url}
    defaults: { _controller: MyUtilsBundle:Redirecting:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET|POST]