imports:
    - { resource: "@MyUserBundle/Resources/config/security.yml" }


security:
    role_hierarchy:
        ROLE_ADMIN:       
            - ROLE_USER
            - ROLE_AUTHOR
            - ROLE_MODO
        ROLE_MODO:        ROLE_USER
        ROLE_SUPER_ADMIN: 
            - ROLE_USER
            - ROLE_MODO 
            - ROLE_AUTHOR           
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    access_control:
        # Routes are prefixed by ther user locale.
        - { path: ^/\w\w/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/event/create, role: ROLE_USER }
        - { path: ^/\w\w/admin/, role: ROLE_ADMIN }
        - { path: ^/\w\w/flashbag/, role: ROLE_ADMIN }