imports:
    - { resource: "@MyUserBundle/Resources/config/security.yml" }


security:
    role_hierarchy:
        ROLE_ASSO:
            - ROLE_USER
        ROLE_BIZNESS:
            - ROLE_USER
        ROLE_ADMIN:       
            - ROLE_USER
            - ROLE_AUTHOR
            - ROLE_MODO
            - ROLE_SONATA_ADMIN
        ROLE_MODO:        ROLE_USER
        ROLE_SUPER_ADMIN: 
            - ROLE_USER
            - ROLE_MODO 
            - ROLE_AUTHOR           
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    access_control:
        # Routes are prefixed by ther user locale.
        # - { path: ^/home, roles: ROLE, ip: X.X.X.X, host: example\.com$, methods: [POST, PUT] }
        - { path: ^/\w\w/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/participant/add/me/, role: ROLE_USER }
        - { path: ^/\w\w/participant/cancel/me/, role: ROLE_USER }
        - { path: ^/\w\w/event/create, role: ROLE_USER }
        - { path: ^/\w\w/invitation/addblacklist, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/invitation/removeblacklist, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/\w\w/invitation/invite/, role: ROLE_USER }
        - { path: ^/\w\w/event/alert/, role: ROLE_USER }
        - { path: ^/\w\w/event/alert/send, role: ROLE_ADMIN }
        - { path: ^/\w\w/world/export*, role: ROLE_ADMIN }
        - { path: ^/\w\w/follower/, role: ROLE_USER }
        - { path: ^/\w\w/profile/, role: ROLE_USER }
        - { path: ^/\w\w/admin/, role: ROLE_ADMIN }
        - { path: ^/\w\w/convert/, role: ROLE_ADMIN }
        - { path: ^/\w\w/flashbag/, role: ROLE_ADMIN }
        - { path: ^/\w\w/stats/, role: ROLE_ADMIN }
