parameters:
#    tuto_animaux.example.class: Tuto\AnimauxBundle\Example

services:
#    tuto_animaux.example:
#        class: %tuto_animaux.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
