parameters:
#    my_comment.example.class: My\CommentBundle\Example

services:
    comment_bundle.listener.comment:
        class: My\CommentBundle\EventListener\CommentListener
        arguments: [@doctrine.orm.entity_manager,@router,@ws_mailer]
        scope: container
        tags:
            - { name: kernel.event_subscriber }
