ws_sports_json:
    pattern:  /json
    defaults: { _controller: WsSportsBundle:Sport:json }

admin_sports_category:
    resource: "@WsSportsBundle/Resources/config/routing/category.yml"
    prefix: /admin/category

admin_sports_sport:
    resource: "@WsSportsBundle/Resources/config/routing/sport.yml"
    prefix: /admin/sport

ws_sports_autocomplete:
    pattern: /sport/autocomplete/{prefix}
    defaults: { _controller: WsSportsBundle:Default:autocomplete, prefix:null }
    requirements:
        _method: GET