parameters:
#    ws_sports.example.class: Ws\SportsBundle\Example

services:
#    ws_sports.example:
#        class: %ws_sports.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    ws_sports_bundle.select_multiple_type:
        class: Ws\SportsBundle\Form\Type\SportSelectMultipleType
        tags:
            - { name: form.type, alias: sport_select_multiple }