class: My\BlogBundle\Entity\Article
repository: MyBlogBundle:Article
relations:
    id: id
    titre: name
    description: content
    date: 
        type: date
        field: created
        format: "Y-m-d h:i:s"