type: entity
class: Ws\EventsBundle\Entity\Event
relations:
    id: id
    title: title
    slug: slug
    online: online
    phone: phone
    nbmin: nbmin
    nbmax: nbmax
    confirmed: confirmed
    description: description
    price: 
        type: integer
        value: 0
    level:
        type: integer
        value: 0
    date:
        type: date
        field: date
        format: "Y-m-d"
    time: 
        type: datetime
        field: time
        format: "H:i:s"
    date_depot: 
        type: date
        field: date_depot
        format: "Y-m-d H:i:s"
    type: 
        type: call
        class: Ws\ConvertSQLBundle\Caller\EventsCaller
        method: setType
    organizer:
        type: call
        class: Ws\ConvertSQLBundle\Caller\EventsCaller
        method: setOrganizer
    serie: 
        type: value
        value: null
    sport: 
        type: call
        class: Ws\ConvertSQLBundle\Caller\EventsCaller
        method: setSport
    occurence:
        type: integer
        value: 1
    spot:
        type: call
        class: Ws\ConvertSQLBundle\Caller\EventsCaller
        method: setSpot
        parameters:
            fields:
                CC1: CC1
                ADM1: ADM1
                ADM2: ADM2
                ADM3: ADM3
                ADM2: ADM4
                city: cityID
    location:
        type: call
        class: Ws\ConvertSQLBundle\Caller\EventsCaller
        method: setLocation

