class: My\PageBundle\Entity\Page
relations:
    id: id_i18n
    title: title
    slug: slug
    content: content
    isOnline: valid
    menu: 
        type: string
        value: bottom
    position: 
        type: integer
        value: 0  