class: Ws\EventsBundle\Entity\Participation
repository: WsEventsBundle:Participation
relations:
    id: id
    event: 
        type: call
        class: Ws\ConvertSQLBundle\Caller\ParticipationsCaller        
        method: getEvent
    user: 
        type: call
        class: Ws\ConvertSQLBundle\Caller\ParticipationsCaller
        method: getUser
    date_inscription: 
        type: date
        field: date
        format: "Y-m-d H:i:s"