type: entity
class: My\UserBundle\Entity\User
repository: MyUserBundle:User
relations:
    location:
        type: call
        class: Ws\ConvertSQLBundle\Caller\LocationCaller
        method: findLocationFromData
    id: user_id
    username: login
    username_canonical: login
    email: email
    email_canonical: email
    roles:
        type: call
        class: Ws\ConvertSQLBundle\Caller\UsersCaller
        method: setRoles
    enabled: valid
    salt: salt
    password: hash
    last_login:
        field: date_lastlogin
        type: datetime
        format: "Y-m-d h:i:s"
    confirmation_token: codeactiv
    type: role
    firstname: prenom
    lastname: nom
    birthday:
        field: birthdate
        type: datetime
        format: "Y-m-d"
    gender: 
        type: call
        class: Ws\ConvertSQLBundle\Caller\UsersCaller
        method: setGender
    description: descr
    register_since: 
        field: date_signin
        type: datetime
        format: "Y-m-d h:i:s"
    lang_prefered: lang
    avatar:
        type: entity
        class: My\UserBundle\Entity\Avatar
        repository: MyUserBundle:Avatar
        relations:
            path: avatar
    settings:
        type: call
        class: Ws\ConvertSQLBundle\Caller\UsersCaller
        method: setSettings

