type: entity
class: My\UserBundle\Entity\User
repository: MyUserBundle:User
relations:
    salt: salt
    type: role
    id: user_id
    email: email
    lastname: nom
    password: hash
    enabled: valid
    username: login
    firstname: prenom
    description: descr
    lang: lang
    email_canonical: email
    username_canonical: login
    confirmation_token: codeactiv
    location:
        type: call
        class: Ws\ConvertSQLBundle\Caller\LocationCaller
        method: findLocationFromData
    roles:
        type: call
        class: Ws\ConvertSQLBundle\Caller\UsersCaller
        method: setRoles
    last_login:
        field: date_lastlogin
        type: datetime
        format: "Y-m-d h:i:s"
    birthday:
        field: birthdate
        type: datetime
        format: "Y-m-d"
    gender: 
        type: call
        class: Ws\ConvertSQLBundle\Caller\UsersCaller
        method: setGender
    register_since: 
        field: date_signin
        type: datetime
        format: "Y-m-d h:i:s"
    avatar:
        type: entity
        class: My\UserBundle\Entity\Avatar
        repository: MyUserBundle:Avatar
        relations:
            path: avatar
    settings:
        type: call
        class: Ws\ConvertSQLBundle\Caller\UsersCaller
        method: setSettings

