services:
    sonata.admin.my.user:
        class: My\UserBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Utilisateurs", label: "Users" }
        arguments:
            - ~
            - My\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [AcmeDemoBundle]]
