fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile


my_user_delete_me:
    pattern: /my/account/delete
    defaults: { _controller: MyUserBundle:User:delete }
    
user_profil_view:
    pattern: /user/{id}/{username}
    defaults: { _controller: MyUserBundle:User:viewProfil }
    requirements:
        id: \d+

user_profil_edit:
    pattern: /my/{action}
    defaults: { _controller: MyUserBundle:User:editProfil, action: 'account' }

my_user_request_activation_mail:
    pattern: /user/request/activation 
    defaults: { _controller: MyUserBundle:User:requestActivationMail }

#admin
admin_user_index:
    pattern: /admin/user/index
    defaults: { _controller: MyUserBundle:Admin:index }