security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false        
        main:
            pattern: ^/
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: fos_user_security_check
                login_path:  fos_user_security_login
            remember_me:
                key :    %secret%
                lifetime: 3000000000
                path:    /
                domain:  ~
            logout:       
                path: fos_user_security_logout
                target: blog_homepage
            switch_user:  true