security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false        
        main:
            pattern: ^/
            anonymous: true
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                check_path: fos_user_security_check
                login_path:  fos_user_security_login
                use_referer: true
                always_use_default_target_path : false
                default_target_path: ws_calendar
                remember_me: true
                success_handler: login_success.handler
            remember_me:
                key :    %secret%
                lifetime: 3000000000
                path:    /
                domain:  ~
            logout:       
                path: fos_user_security_logout
                target: ws_calendar
                success_handler: logout_success.handler
            switch_user:  true
            entry_point: entry_point.user_login
            oauth:
                resource_owners:
                  facebook: "/login/check-facebook"
                login_path: /oauth-connect
                failure_path: /oauth-connect
                oauth_user_provider:
                  service: rkueny.oauth.user_provider