parameters:
#    tuto_user.example.class: Tuto\UserBundle\Example

services:
    #Handler
    entry_point.user_login:
        class: My\UserBundle\Service\LoginEntryPoint
        arguments: [@router]
    login_success.handler:
        class: My\UserBundle\Service\LoginSuccessHandler
        arguments: [@router,@security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    logout_success.handler:
        class: My\UserBundle\Service\LogoutSuccessHandler
        arguments: [@router,@security.context]
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    #OAuth
    my_user.oauth.user_provider:
        class: My\UserBundle\Providers\OAuth\UserProvider
        arguments: 
            - @fos_user.user_manager
            - { facebook: facebookId }
    my_user.oauth.success_handler:
        class: My\UserBundle\Service\OAuthSuccessHandler
        arguments: [@router,@security.context,@flashbag]


    #Form Type
    my_user.registration.form.type:
        class: My\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%,@router]
        tags:
            - { name: form.type, alias: my_user_registration }

    my_user.profile.form.type:
        class: My\UserBundle\Form\Type\ProfilEditionType
        arguments: [@request_stack,@security.context]
        tags:
            - { name: form.type, alias: my_user_profile }

    user_avatar.form.type:
        class: My\UserBundle\Form\Type\AvatarType
        arguments: [@security.context]
        tags:
            - { name: form.type, alias: avatar_type }
    #Mailer
    my_user.mailer:
        class: My\UserBundle\Mailer\Mailer
        arguments: [@mailer,@templating,@router]


   #Form Extension
    user_bundle.image_type_extension:
        class: My\UserBundle\Form\Extension\ImageTypeExtension
        tags:
            - { name: form.type_extension, alias: file }

    #Event Listner
    user_bundle.listener.registration:
        class: My\UserBundle\EventListener\RegistrationListener
        arguments: [@doctrine.orm.entity_manager,@router,@flashbag]
        scope: container
        tags:
            - { name: kernel.event_subscriber }
    user_bundle.listener.profile:
        class: My\UserBundle\EventListener\ProfileListener
        arguments: [@doctrine.orm.entity_manager,@router,@flashbag]
        scope: container
        tags:
            - { name: kernel.event_subscriber }

    #Twig extension
    user.twig.link:
        class: My\UserBundle\Twig\UserProfilLinkExtension
        arguments: [@router]
        tags:
            - { name: twig.extension }