parameters:
#    tuto_user.example.class: Tuto\UserBundle\Example

services:
    acme_user.registration.form.type:
        class: Tuto\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: my_user_registration }
#    tuto_user.example:
#        class: %tuto_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
