parameters:
#    tuto_user.example.class: Tuto\UserBundle\Example

services:
    entry_point.user_login:
        class: My\UserBundle\Service\LoginEntryPoint
        arguments: [@router]


    acme_user.registration.form.type:
        class: My\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: my_user_registration }

    user_bundle.listener.init_registration:
        class: My\UserBundle\Service\RegistrationListener
        arguments: [@doctrine.orm.entity_manager]
        scope: container
        tags:
            - { name: kernel.event_subscriber }
