my_page_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MyPageBundle:Default:index }

MyPageBundle_view:
    pattern: /page/view/{id}
    defaults: { _controller: MyPageBundle:Default:view }
    requirements:
        id: \d+ 


MyPageBundle_page:
    resource: "@MyPageBundle/Resources/config/routing/page.yml"
    prefix: /page/admin

MyPageBundle_contact:
    pattern: /contact
    defaults: { _controller: MyPageBundle:Default:contact }
    requirements:
        _method: GET|POST