MyPageBundle_view:
    pattern: /page/{slug}
    defaults: { _controller: MyPageBundle:Page:view }

MyPageBundle_page:
    resource: "@MyPageBundle/Resources/config/routing/page.yml"
    prefix: /page/admin
