services:
    my_page.menu_builder:
        class: My\PageBundle\Menu\Builder
        arguments: ["@knp_menu.factory","@doctrine.orm.entity_manager"]

    my_page.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: my_page.menu_builder
        factory_method: createMainMenu
        #arguments: ["@request"]
        #scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu


#Twig extension
    page.twig.link:
        class: My\PageBundle\Twig\PageLinkExtension
        arguments: [@router]
        tags:
            - { name: twig.extension }