<?php

namespace My\WorldBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
	public function findCityByUNI($uni)
	{
		$qb = $this->createQueryBuilder('c');
		$qb->where(
			$qb->expr()->eq('c.UNI',':UNI')
			);
		$qb->setParameter('UNI',$uni);
		
		return $qb->getQuery()->getSingleResult();

	}
	public function findCitiesSuggestions( $limit, $prefix , $country = null, $region = null, $dpt = null){

		$qb = $this->createQueryBuilder('c');

		if(isset($country))
		{
			$qb->andWhere(
				$qb->expr()->eq('c.CC1',$qb->expr()->literal($country))
			);			
		}

		if(isset($region))
		{
			$qb->andWhere(
				$qb->expr()->eq('c.ADM1',$qb->expr()->literal($region))
			);			
		}

		if(isset($dpt))
		{
			$qb->andWhere(
				$qb->expr()->eq('c.ADM2',$qb->expr()->literal($dpt))
			);			
		}

		$qb->andWhere(
			$qb->expr()->like('c.FULLNAMEND',$qb->expr()->literal($prefix.'%'))
			);

		$qb->setMaxResults( $limit );

		$qb->orderBy('c.FULLNAMEND','ASC');


		return $qb->getQuery()->getResult();

	}
}
