<?php

namespace My\WorldBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends EntityRepository
{

	public function findAllCountry(){

	    $qb = $this->_em->createQueryBuilder()
	                              ->select('c')
	                              ->from($this->_entityName, 'c');


	    return $qb->getQuery()->getResult();
	}

	public function findListCountry()
	{
		$qb = $this->_em->createQueryBuilder()
							->select('c.id, c.name')
							->from($this->_entityName,'c');

		$p = $qb->getQuery()->getArrayResult();
		$r = array();
		foreach($p as $v){
			$r[$v['id']] = $v['name'];
		}

		return $r;
	}

	public function findCountryByCode($CC1)
	{

		$qb = $this->createQueryBuilder('c');

		$qb->select('c')
			->where(
				$qb->expr()->eq('c.code',':CC1')
				);

		$qb->setParameter('CC1',$CC1);

		return $qb->getQuery()->getSingleResult();
	}

	public function findCountryById($id)
	{

		$qb = $this->createQueryBuilder('c');

		$qb->select('partial c.{id,code,name,lang}')
			->where(
				$qb->expr()->eq('c.id',':id')
				);

		$qb->setParameter('id',$id);

		return $qb->getQuery()->getSingleResult();
	}



}

?>