<?php

namespace My\WorldBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends EntityRepository
{
	public function findWorldLocationOf($object)
	{

		//Si l'object a une methode getLocation
		if(in_array('getLocation',get_class_methods($object))){

			$location = $object->getLocation();

			//Si cest une class de Location
			if($location instanceof Location){

				return $this->findAllDataFromLocation($location);

			}
			else{
				exit('not instanceof Location');
			}
		}
		else{
			
			return $this->findAllDataFromCode($object);
		}

		return array();

	}

	public function findAllDataFromLocation(Location $loc)
	{
		$locations = array();
		$locations['country'] = $this->_em->getRepository("MyWorldBundle:Country")->findOneById($loc->getCountry());			
		$locations['region'] = $this->_em->getRepository('MyWorldBundle:State')->findOneById($loc->getRegion());
		$locations['departement'] = $this->_em->getRepository('MyWorldBundle:State')->findOneById($loc->getDepartement());
		$locations['district'] = $this->_em->getRepository('MyWorldBundle:State')->findOneById($loc->getDistrict());
		$locations['division'] = $this->_em->getRepository('MyWorldBundle:State')->findOneById($loc->getDivision());
		$locations['city'] = $this->_em->getRepository('MyWorldBundle:City')->findOneById($loc->getCity());
		
		return $locations;
	}

	public function findAllDataFromCode($obj){

		$locations = array();

		if(!empty($obj->CC1))
		{
			$locations['country'] = $this->_em->getRepository('MyWorldBundle:Country')->findCountryByCode($obj->CC1);
		}

		if(!empty($obj->ADM1))
		{
			$locations['region'] = $this->_em->getRepository('MyWorldBundle:State')->findStateByCodes($obj->CC1,$obj->ADM1,'ADM1');
		}

		if(!empty($obj->ADM2))
		{
			$locations['departement'] = $this->_em->getRepository('MyWorldBundle:State')->findStateByCodes($obj->CC1,$obj->ADM2,'ADM2');
		}

		if(!empty($obj->ADM3))
		{
			$locations['district'] = $this->_em->getRepository('MyWorldBundle:State')->findStateByCodes($obj->CC1,$obj->ADM3,'ADM3');
		}

		if(!empty($obj->ADM4))
		{
			$locations['division'] = $this->_em->getRepository('MyWorldBundle:State')->findStateByCodes($obj->CC1,$obj->ADM4,'ADM4');
		}

		if(!empty($obj->city))
		{
			$locations['city'] = $this->_em->getRepository('MyWorldBundle:City')->findCityByUNI($obj->city);
		}

		return $locations;
	}
	
}
