<?php

namespace My\WorldBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends EntityRepository
{
	
	public function findStateByCodes($CC1,$ADM1,$ADM2 = null,$ADM3 = null,$ADM4 = null)
	{
		if(!empty($ADM4))
			return $this->findStateByCode($CC1,$ADM4,'ADM4');
		if(!empty($ADM3))
			return $this->findStateByCode($CC1,$ADM3,'ADM3');
		if(!empty($ADM2))
			return $this->findStateByCode($CC1,$ADM2,'ADM2');
		if(!empty($ADM1))
			return $this->findStateByCode($CC1,$ADM1,'ADM1');
	}

	public function findStateByCode($CC1, $code, $level)
	{
		//return empty State if no code specified
		if(empty($code)) return new State();

		$q = $this->getEntityManager()->createQuery("
			SELECT s 
			FROM MyWorldBundle:State s
			JOIN MyWorldBundle:Country c
			WITH c.code = s.CC1
			WHERE s.CC1 = :CC1			
			AND s.ADM_CODE = :code
			AND s.DSG = :level
			AND s.lang = c.lang
			");

		$q->setParameters(array(
			'CC1'=>$CC1,
			'code'=>$code,
			'level'=>$level)
		);

		return $q->getSingleResult();
	}

	public function findStatesByParent($level, $CC1, $parent = '')
	{
		$q = $this->getEntityManager()->createQuery("
			SELECT s 
			FROM MyWorldBundle:State s 
			JOIN MyWorldBundle:Country c 
			WITH c.code = s.CC1 
			WHERE s.CC1 = :CC1 
			AND s.ADM_PARENT = :parent
			AND s.DSG = :level
			AND s.lang = c.lang
			");

		$q->setParameters(array(
			'CC1'=>$CC1,
			'parent'=>$parent,
			'level'=>$level
			));

		return $q->getResult();
	}

}
