<?php

namespace My\WorldBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends EntityRepository
{
	public function findStateByName($name,$countryCode = null)
	{
		$sql = "
			SELECT s
			FROM MyWorldBundle:State s
			JOIN MyWorldBundle:Country c
			WITH c.code = s.cc1
			AND s.name = :name
			AND s.lang = c.lang ";
		if(isset($countryCode)) $sql .= " AND s.cc1 = :cc1 ";

		$q = $this->getEntityManager()->createQuery($sql);
		$q->setParameter('name',$name);
		if(isset($countryCode)) $q->setParameter('cc1',$countryCode);

		return $q->getOneOrNullResult();
	}

	public function findStateByCodes($cc1,$adm1,$adm2 = null,$adm3 = null,$adm4 = null)
	{
		if(!empty($adm4))
			return $this->findStateByCode($cc1,$adm4,'ADM4');
		if(!empty($adm3))
			return $this->findStateByCode($cc1,$adm3,'ADM3');
		if(!empty($adm2))
			return $this->findStateByCode($cc1,$adm2,'ADM2');
		if(!empty($adm1))
			return $this->findStateByCode($cc1,$adm1,'ADM1');
	}

	public function findStateByCode($cc1, $code, $level)
	{
		//return empty State if no code specified
		if(empty($code)) return new State();

		$q = $this->getEntityManager()->createQuery("
			SELECT s 
			FROM MyWorldBundle:State s
			JOIN MyWorldBundle:Country c
			WITH c.code = s.cc1
			WHERE s.cc1 = :cc1			
			AND s.adm_code = :code
			AND s.dsg = :level
			AND s.lang = c.lang
			");

		$q->setParameters(array(
			'cc1'=>$cc1,
			'code'=>$code,
			'level'=>$level)
		);

		$results = $q->getResult();
		
		return $results[0];
	}

	public function findStatesByParent($level, $cc1, $parent = '')
	{
		$q = $this->getEntityManager()->createQuery("
			SELECT s 
			FROM MyWorldBundle:State s 
			JOIN MyWorldBundle:Country c 
			WITH c.code = s.cc1 
			WHERE s.cc1 = :cc1 
			AND s.adm_parent = :parent
			AND s.dsg = :level
			AND s.lang = c.lang
			");

		$q->setParameters(array(
			'cc1'=>$cc1,
			'parent'=>$parent,
			'level'=>$level
			));

		return $q->getResult();
	}

}
