ws_events_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: WsEventsBundle:Default:index }

ws_events_view:
    pattern: /view/{event}
    defaults: { _controller: WsEventsBundle:Default:view }
    requirements:
        event: \d+

ws_events_new:
    pattern: /new
    defaults: { _controller: WsEventsBundle:Default:new }

ws_events_delete:
    pattern: /delete/{event}/{token}
    defaults: { _controller: WsEventsBundle:Default:delete }
    requirements:
        event: \d+


ws_events_week_ajax:
    pattern: /calendar/ajax/{date}
    defaults: { _controller: WsEventsBundle:Default:weekAjax, date:'now'}
    requirements:         
        _method: GET


ws_events_calendar:
    pattern: /calendar/{country}/{city}/{sports}/{type}/{nbdays}/{date}
    defaults: { _controller: WsEventsBundle:Default:calendar, country:null, city:null, sports:null, date:null, nbdays:null, type:null }
    requirements:         
        _method: GET



#===========
#  Admin
#===========
admin_ws_events_index:
    pattern: /admin/index
    defaults: { _controller: WsEventsBundle:Admin:index }

admin_ws_events_unpublish:
    pattern: /admin/unpublish/{event}
    defaults: { _controller: WsEventsBundle:Admin:desactivate }

admin_ws_events_publish:
    pattern: /admin/publish/{event}
    defaults: { _controller: WsEventsBundle:Admin:activate }

admin_ws_events_delete:
    pattern: /admin/delete/{event}
    defaults: { _controller: WsEventsBundle:Admin:delete }