#EVENTS
ws_events_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: WsEventsBundle:Event:index }

ws_events_view:
    pattern: /view/{event}
    defaults: { _controller: WsEventsBundle:Event:view }
    requirements:
        event: \d+
ws_events_new:
    pattern: /create
    defaults: { _controller: WsEventsBundle:Event:create }
ws_events_delete:
    pattern: /delete/{event}/{token}
    defaults: { _controller: WsEventsBundle:Event:delete }
    requirements:
        event: \d+

#CALENDAR
ws_events_calendar_ajax:
    pattern: /calendar/ajax/{date}
    defaults: { _controller: WsEventsBundle:Calendar:ajax, date:'now'}
    requirements:         
        _method: GET
ws_events_calendar_reset:
    pattern: /calendar/reset
    defaults: { _controller: WsEventsBundle:Calendar:reset}
    requirements:         
        _method: GET
ws_events_calendar:
    pattern: /calendar/{date}/{city}/{sports}/{type}/{nbdays}/{time}/{price}/{organizer}
    defaults: { _controller: WsEventsBundle:Calendar:load, city:null, sports:null, date:null, nbdays:null, type:null, time:null, price:null, organizer:null }
    requirements:         
        _method: GET
ws_events_calendar_update:
    pattern: /calendar/update
    defaults: { _controller:WsEventsBundle:Calendar:update }
    requirements:
        _method: POST

#INVITATION
ws_new_invitations:
    pattern: /invite/{event}
    defaults: { _controller: WsEventsBundle:Invitation:create}
    requirements:
        event: \d+
ws_invitations_add_blacklist:
    pattern: /invitation/addblacklist/{emails}
    defaults: { _controller: WsEventsBundle:Invitation:addBlacklist, emails: null }
ws_invitations_remove_blacklist:
    pattern: /invitation/removeblacklist/{emails}
    defaults: { _controller: WsEventsBundle:Invitation:removeBlacklist, emails: null}
ws_invited_confirm:
    pattern: /invite/confirm/{invited}
    defaults: { _controller: WsEventsBundle:Invitation:confirmParticipation }
    requirements:
        invited: \d+
ws_invited_deny:
    pattern: /invite/deny/{invited}
    defaults: { _controller: WsEventsBundle:Invitation:denyParticipation }
    requirements:
        invited: \d+

#ALERTS
ws_events_create_alert:
    pattern: /alert/create
    defaults: { _controller: WsEventsBundle:Alert:create }
    requirements:
        _method: GET|POST
ws_events_index_alert:
    pattern: /alert/index
    defaults: { _controller: WsEventsBundle:Alert:index }
    requirements:
        _method: GET
ws_events_delete_alert:
    pattern: /alert/delete/{alert}
    defaults: { _controller: WsEventsBundle:Alert:delete }
    requirements:
        _method: GET|POST
ws_alerts_daily_mailing:
    pattern: /alert/send/daily
    defaults: { _controller: WsEventsBundle:Alert:dailyAlerting }

#===========
#  Admin
#===========
admin_ws_events_index:
    pattern: /admin/index
    defaults: { _controller: WsEventsBundle:Admin:index }

admin_ws_events_unpublish:
    pattern: /admin/unpublish/{event}
    defaults: { _controller: WsEventsBundle:Admin:desactivate }

admin_ws_events_publish:
    pattern: /admin/publish/{event}
    defaults: { _controller: WsEventsBundle:Admin:activate }

admin_ws_events_delete:
    pattern: /admin/delete/{event}
    defaults: { _controller: WsEventsBundle:Admin:delete }