parameters:
    ws_events.event.form : Ws\EventsBundle\Form\Type\EventType

services:
#    ws_events.example:
#        class: %ws_events.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    #Formulaire
    ws_events.form.type.event:
        class: %ws_events.event.form%        
        tags:
            - { name: form.type, alias: event }
    ws_events.form.type.serie:
        class: Ws\EventsBundle\Form\Type\SerieType      
        tags:
            - { name: form.type, alias: serie }

    ws_events.form.type.invitations:
        class: Ws\EventsBundle\Form\Type\InvitationsType
        arguments: [@doctrine.orm.entity_manager,@security.context,@router]
        tags:
            - { name: form.type, alias: invitations_type }

    ws_events.form.type.alert:
        class: Ws\EventsBundle\Form\Type\AlertType     
        arguments: [@security.context]
        tags:
            - { name: form.type, alias: alert_type }

    ws_events.form.type.search:
        class: Ws\EventsBundle\Form\Type\CalendarSearchType 
        arguments: [@calendar.manager,@security.context,@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: calendar_search_type }

    ws_events.form.type.spot:
        class: Ws\EventsBundle\Form\Type\SpotType   
        arguments: [@doctrine.orm.entity_manager,@router]
        tags:
            - { name: form.type, alias: spot_type }

    #Managers
    ws_events.manager:
        class: Ws\EventsBundle\Manager\EventManager
        arguments: [@service_container]

    calendar.manager:
        class: Ws\EventsBundle\Manager\CalendarManager
        arguments: [@service_container]

    calendar.url.generator:
        class: Ws\EventsBundle\Manager\CalendarUrlGenerator
        arguments: [@router]

    ws_events.invit.manager:
        class: Ws\EventsBundle\Manager\InvitationManager
        arguments: [@service_container]

    ws_events.alert.manager:
        class: Ws\EventsBundle\Manager\AlertManager
        arguments: [@service_container]

    ws_events.spot.manager:
        class: Ws\EventsBundle\Manager\SpotManager
        arguments: [@service_container]

    #Twig
    ws_events.twig.eventlink:
        class: Ws\EventsBundle\Twig\EventLinkExtension
        arguments: [@router]
        tags:
            - { name: twig.extension }
    ws_events.twig.alertResume:
        class: Ws\EventsBundle\Twig\AlertResumeExtension
        arguments: [@translator]
        tags:
            - { name: twig.extension }

    #Event Listner
    ws_events.listener.events:
        class: Ws\EventsBundle\EventListener\EventsListener
        arguments: [@doctrine.orm.entity_manager,@router,@flashbag,@ws_mailer]
        scope: container
        tags:
            - { name: kernel.event_subscriber }
    ws_events.listener.invitation:
        class: Ws\EventsBundle\EventListener\InvitationListener
        arguments: [@doctrine.orm.entity_manager,@router,@flashbag,@ws_mailer]
        scope: container
        tags:
            - { name: kernel.event_subscriber }
    ws_events.listener.participation:
        class: Ws\EventsBundle\EventListener\ParticipationListener
        arguments: [@doctrine.orm.entity_manager,@router,@flashbag,@ws_mailer]
        scope: container
        tags:
            - { name: kernel.event_subscriber }

    #Enable Init Method for all the controller that implements InitControllerInterface
    symfony.controller.subscriber.init:
        class: Yavin\Symfony\Controller\InitControllerSubscriber
        tags: 
            - { name: kernel.event_subscriber }
