parameters:
#    ws_events.example.class: Ws\EventsBundle\Example

services:
#    ws_events.example:
#        class: %ws_events.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
