parameters:
    ws_events.event.form : Ws\EventsBundle\Form\Type\EventType

services:
#    ws_events.example:
#        class: %ws_events.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    ws_events.form.type.event:
        class: %ws_events.event.form%        
        tags:
            - { name: form.type, alias: event }
    ws_events.form.type.serie:
        class: Ws\EventsBundle\Form\Type\SerieType      
        tags:
            - { name: form.type, alias: serie }
    ws_events.manager:
        class: Ws\EventsBundle\Manager\EventManager
        arguments: [@doctrine.orm.entity_manager,@security.context]

    ws_events.twig.eventlink:
        class: Ws\EventsBundle\Twig\EventLinkExtension
        arguments: [@router]
        tags:
            - { name: twig.extension }
