parameters:
#    ws_mailer.example.class: Ws\MailerBundle\Example

services:
#    ws_mailer.example:
#        class: %ws_mailer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    #MAILER
    ws_mailer:
        class: Ws\MailerBundle\Mailer\mailer
        arguments: [@mailer,@templating]
        tags:
            - { name: ws_mailer, alias: ws_mailer }
    #MANAGER
    ws_mailer.settings.manager:
        class: Ws\MailerBundle\Manager\SettingsManager
        arguments: [@service_container]

    #FORM
    ws_mailer.settings.form.type:
        class: Ws\MailerBundle\Form\Type\WsMailerSettingsType 
        arguments: [@security.context]
        tags:
            - { name: form.type, alias: ws_mailer_settings_type }