<?php

namespace My\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	public function countAll()
	{
		return $this->createQueryBuilder('u')
				 ->select('COUNT(u)')
				 ->getQuery()
				 ->getSingleScalarResult();
	}
}
