my_world_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MyWorldBundle:Default:index }

my_world_test:
    pattern: /test
    defaults: { _controller: MyWorldBundle:Default:test }

my_world_nextlevel:
    pattern: /nextStateLevel
    defaults: { _controller: MyWorldBundle:Default:nextStatesLevel }
    requirements:
        _method: GET

my_world_autocompletecity:
    pattern: /autocompletecity/{country}/{prefix}
    defaults: { _controller: MyWorldBundle:City:autoComplete, country:'FR', prefix:'' }
    requirements:
        _method: GET