my_world_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: MyWorldBundle:Default:index }

my_world_location_select_test:
    pattern: /location/select
    defaults: { _controller: MyWorldBundle:Location:formSelectLocation }

my_world_location_select_nextlevel:
    pattern: /location/levelchildren
    defaults: { _controller: MyWorldBundle:Location:nextGeoLevel }
    requirements:
        _method: GET

my_world_city_search:
    pattern: /city/search
    defaults: { _controller: MyWorldBundle:City:search }
    requirements:
        _method: GET|POST

my_world_city_view:
    pattern: /city/view/{city}
    defaults: { _controller: MyWorldBundle:City:view }
    requirements:
        _method: GET

my_world_location_nearest:
    pattern: /location/near/{lat}/{lon}/{country}
    defaults: { _controller: MyWorldBundle:Location:nearestLatLon, country: France }
    requirements:
        _method: GET


my_world_autocompletecity:
    pattern: /city/autocomplete/{country}/{prefix}
    defaults: { _controller: MyWorldBundle:City:autoComplete, country:'FR', prefix:'' }
    requirements:
        _method: GET