parameters:
#    my_world.example.class: My\WorldBundle\Example

services:
#    my_world.example:
#        class: %my_world.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    world.form.type.autocompletecity:
        class: My\WorldBundle\Form\Type\AutoCompleteCityType       
        tags:
            - { name: form.type, alias: autoCompleteCity }

    world.location_manager:
        class: My\WorldBundle\Manager\LocationManager
        arguments: [@doctrine.orm.entity_manager]