parameters:
#    my_world.example.class: My\WorldBundle\Example

services:
#    my_world.example:
#        class: %my_world.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    world.form.type.autocompletecity:
        class: My\WorldBundle\Form\Type\CityToLocationType 
        arguments: [@doctrine.orm.worlddb_entity_manager,@router]
        tags:
            - { name: form.type, alias: city_to_location_type }

    world.form.type.locationSelectType:
        class: My\WorldBundle\Form\Type\LocationSelectType
        arguments: [@doctrine.orm.worlddb_entity_manager,@router]
        tags:
            - { name:form.type, alias: location_select }

    world.location_manager:
        class: My\WorldBundle\Manager\LocationManager
        arguments: [@doctrine.orm.worlddb_entity_manager]

    world.map_manager:
        class: My\WorldBundle\Geomapper\MapManager
        arguments: [@service_container]

    world.gmap:
        class: My\WorldBundle\Geomapper\GoogleMapAPI        

    world.locationip.service:
        class: My\WorldBundle\Controller\LocationFromIpController
        arguments: [@service_container]