<?php

namespace My\PageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
	public function findByMenu($menu)
	{
		$qb = $this->_em->createQueryBuilder('p');
	    $qb->select('p')
	    ->from($this->_entityName, 'p')
	    ->where($qb->expr()->eq('p.menu',':menu'))
	    ;
	    $qb->setParameter('menu',$menu);

	    return $qb->getQuery()->getResult();
	}

	public function findSingleBySlug($slug)
	{
		$qb = $this->_em->createQueryBuilder('p');
	    $qb->select('p')
	    ->from($this->_entityName, 'p')
	    ->where($qb->expr()->eq('p.slug',':slug'))
	    ;
	    $qb->setParameter('slug',$slug);

	    return $qb->getQuery()->getSingleResult();
	}
}

?>