parameters:
#    my_manager.example.class: My\ManagerBundle\Example

services:
#    my_manager.example:
#        class: %my_manager.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
