<?php

namespace Ws\SportsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends EntityRepository
{
	public function autocomplete($prefix)
	{
		$qb = $this->createQueryBuilder('s');

		$qb->innerJoin('s.category','c');

		$qb->andWhere($qb->expr()->like('s.name',':prefix'));
		$qb->orWhere($qb->expr()->like('s.keywords',':prefix'));
		$qb->orWhere($qb->expr()->like('c.keywords',':prefix'));

		$qb->setParameter('prefix','%'.$prefix.'%');
		
		return $qb->getQuery()->getResult();

	}	
}

?>