<?php

namespace Ws\SportsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SportRepository extends EntityRepository
{
	public function autocomplete($prefix)
	{
		$qb = $this->createQueryBuilder('s');
		$qb->where(
			$qb->expr()->like('s.name',$qb->expr()->literal('%'.$prefix.'%'))
			);

		return $qb->getQuery()->getResult();

	}	
}

?>